### ISSUE TITLE
runtime failure

### ISSUE THREAD

**Issue by zingale** [rickyfernandez/phd-code#2]
When I run `run_sim.py` using python 3.6.5, I get:
```
$ python3 run_sim.py 
/usr/lib64/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
TypeError: 'dict_values' object does not support indexing
Exception ignored in: 'phd.containers.containers.CarrayContainer.get_carray_size'
TypeError: 'dict_values' object does not support indexing
Traceback (most recent call last):
  File "run_sim.py", line 60, in <module>
    particles = create_particles()
  File "run_sim.py", line 25, in create_particles
    particles = phd.HydroParticleCreator(n)
  File "phd/utils/particle_creator.pyx", line 17, in phd.utils.particle_creator.HydroParticleCreator
    pc.register_carray(num, 'position-' + axis, 'double')
  File "phd/containers/containers.pyx", line 58, in phd.containers.containers.CarrayContainer.register_carray
    raise RuntimeError("ERROR: Size inconsistent with carray size")
RuntimeError: ERROR: Size inconsistent with carray size
```

I have:
NumPy 1.14.5
CGAL 4.11.1
boost 1.66.0-7

**Comment by rickyfernandez** [comment]
I removed this file as it is no longer consistent. Can you cd to the directory

test_suite/sod/2d/cartesian

and try 

python sod_2d_cartesian.py 

using python 2.7 (the code does not work with python 3 yet). Thanks
for trying out the code, you are first person to do so!

**Comment by zingale** [comment]
indeed.  It works with python 2.7, so this is a python 3 issue.  You should add a note to the README.md that it only works with python 2, not python 3.

Thanks
